# Generated by Django 4.1 on 2023-05-29 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_specificity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurieTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CurieTemplateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=128)),
                ('curie_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene_specificity.curietemplate')),
            ],
        ),
    ]
